# ワークフロー名
name: manaba_bot

on:
  workflow_dispatch:
# on:
#   schedule: 
#     # 定期実行する時間・・・①
#     - cron: '0 3 * * *'
    
env:
 CHANNEL_ACCESS_TOKEN: ${{secrets.CHANNEL_ACCESS_TOKEN}}
 USER_ID: ${{secrets.USER_ID}}
 username: ${{secrets.username}}
 password: ${{secrets.password}}
 
jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt update
          sudo apt-get install google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install line-bot-sdk
          pip install beautifulsoup4
          pip install selenium
          
      - name: Run script
        run: |
          # 定期実行するファイルを指定。
          python main.py
